name: flserial
description: "Flutter Serial Port Plugin FFI based on great C library. Useful to communicate with RS232 devices."
version: 0.2.0
homepage: "https://github.com/grzesl/flserial"

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.2
dev_dependencies:
  ffigen: ^11.0.0
  test: ^1.25.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# This package supports only Linux and macOS.
platforms:
  android:
  linux:
  windows:
